### ISSUE TITLE
`Serialization` folder

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#125]
### Motivation
Model files should be **declarative**. Using a function inside a model is not allow that defining models in **JSON** or **YAML** format. Currently, we can write the same model as JSON or YAML except for the `serialization` function.

### Tasks
- [x] Add a `Serialization` folder to the `app` directory.
- [x] Developers should be able to serialization function with model names like `UserSerialization.js`
- [x] In the initialization process we should read that folder and all serialization functions, and bind them to the models. 
- [x] We should use the new serialization function rather than old structure. 
- [x] We should remove the serialization definitions from the base `Model`.
- [x] The documentation should be updated. (https://github.com/axe-api/docs/pull/51)
