### ISSUE TITLE
Version management on the API

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#137]
Version management is getting a bigger issue day by day. In this issue, we are going to discuss it and try to add some solutions.

### Motivation

Developers should be able to add multiple versions to define some endpoint, fields, or features as `deprecated` to notify the clients before the actual change has been implemented. Also, developers should be able to remove/add a feature after a specific version to make the API more maintainable. 

Mistakes happen. We should allow developers to fix them for the next versions.

### Suggestions

The current `app` folder structure is like this;

```js
.
├── Config
├── Events
├── Hooks
├── Models
init.ts 
```

To support multiple API versions, developers should structure their codes like this;

```js
.
├── Config
├── Http
  ├── v1
    ├──  Events
    ├──  Hooks
    ├──  Models
    init.ts
  ├── v2
    ├──  Events
    ├──  Hooks
    ├──  Models
    init.ts
```

We should put the `Events`, `Hooks`, `Models` folders, and the `init.ts` file in the version folders. Because those completely change the business logic. For example;
- In the `init.ts` file developers add some middleware, custom routes, etc.
- In the `Models` folders developers change all of the API structure.
- In the `Events` and `Hooks` folders developers can change all the business logic.

### Problems

Currently, we have different kinds of config structures. For example  `Database.ts` can be the same for all the versions. Because even though developers want to use different databases for different versions, it is unlikely. 

But for example; transaction structure, common serializer, and supported languages are able to be changed by the version. But the `prefix` value can not be changed. It almost should stay the same for all versions. 

So basically, we should have different kinds of configs;
- App general config
- Version general configs

We should restructure all application folders. And this is a huge change, it will require too many changes. 

### New Features with New Version

If developers remove some features in the new version after they marked them as `deprecated` in the previous version, that's totally ok. The Axe API framework does not have to do anything.

But adding new features or changes should be marked on the documentation. Currently, we have a documentation issue. We should decide how we handle this problem while we are developing the auto-documentation feature.

https://github.com/axe-api/axe-api/issues/138

### Todo List

- [x] Split configuration files into two types; `General`, and `VersionSpecefic`.
- [x] Read configuration files by types.
- [x] Creating/handling routes for multiple versions. 
- [x] Check version name (alpha_numeric)
- [x] The documentation should be updated.
- [x] New migration guide should be updated
api/v/0.30.0-rc1)
- [x] The `axe-api-template` should be updated.
- [x] The `dev-kit` should be updated.
