### ISSUE TITLE
Soft deleting

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#41]
### What is a soft delete?

A soft delete marks a record as no longer active or valid without actually deleting it from the database. Soft deletes can improve performance, and can allow “deleted” data to be recovered. [[*]](https://www.metabase.com/glossary/soft_delete)

### Motivations

Developers should be able to add soft-delete features to the models.  

### Implementation

To add a soft-delete feature to a model, developers must add the following code to the model file;

```js
class User extends Model {
  get deletedAtColumn(): string {
    return "deleted_at";
  }
}

```

`deletedAtColumn` should return `NULL` from the base `Model`. If developers add a database field name, it means that we have a soft-deleting feature for this model. Developers must create a `timestamps` data field on the database via migrations. 

### Soft-Deleting Record

The `DELETE` handler must work as the soft-deleting if there is soft-deleting support. Otherwise, it must work like a normal delete. 

On the other hand, developers should be able to add `FORCE_DELETE` handler to models like the following example to support the force delete feature;

```js
const { INSERT, PAGINATE, DELETE, FORCE_DELETE } = HandlerTypes;

class User extends Model {
  get handlers(): HandlerTypes[] {
    return [INSERT, PAGINATE, DELETE, FORCE_DELETE];
  }
}
```

### Queries

Clients should not be able to see the soft-deleted records in queries (`PAGINATE`, `SHOW`).  Also, clients should not be able to manipulate the soft-deleted records (`UPDATE`, `PATCH`). 

In addition, the `with` keyword that fetches the related data should work with the soft-deleting feature perfectly. 

Also, related data fetch must work perfectly with soft deleting. For example; the `/api/users/1/posts` request should check if the `user 1` is soft-deleted or not. (#132)

### Force Delete Handler

This would be a new handler for force deleting. 

```
DELETE /api/users/:id/force
```

### Listing deleted values

Clients should be able to fetch soft-deleted records from a database. To do that, they must use the following command;

```js
/api/users?trashed=true
```

> This should be configurable. By default, it should be false. 

### Hooks & Events

The following hooks and events should be supported for the force-delete handler;

- onBeforeForceDeleteQuery
- onAfterForceDeleteQuery
- onBeforeForceDelete
- onAfterForceDelete

### Todo List

- [x] Add the` deletedAtColumn` column to the base `Model`
- [x] Change the `DELETE` handler works.
- [x] Add the `FORCE_DELETE` handler.
- [x] Change the basic queries.
- [x] Change the `with` operator works.
- [x] Add the `trashed` parameter to the queries.
- [x] Check the soft-deleting feature for `PUT`, `PATCH`
- [x] Add new hooks. 
- [x] Add the related query checks for the soft-deleting feature (`/api/users/1/posts`)

### Acceptance Criteria

- [x] Users should be able to soft delete (DELETE)
- [x] Users should not be able to see the soft-deleted records (PAGINATE, SHOW, ALL)
- [x] Users should not be able to update the soft-deleted records (PUT, PATCH)
- [x] Users should be able to force-delete a record (FORCE_DELETE)
- [x] Users should be able to see all records for non-soft-delete models (PAGINATE, SHOW, ALL)
- [x] Users should not be able to see soft deleted records (`/api/users/1/customers` => Customer)
- [x] Users should not be able to see soft deleted records (`/api/users?with=customers` => Customer)
- [x] Users should not be able to handle child element if the parent record has been soft-deleted (`/api/customers/1/phones` => Customer)
- [x] Users should not be able to handle records if related-parent elements (`/api/phones?with=customer` => Customer)
- [x] Users should be able to use force-delete hooks
- [x] Users should be able to see the `trashed` record by the query parameters (PAGINATE, SHOW, ALL)

### Documentation Change

- [x] Models -> Soft Deleting
- [x] Handlers
- [x] Queries -> trashed
- [x] Queries -> related data
- [x] Hooks
- [x] DB Analyzer

**Comment by ozziest** [comment]
> #38 , `trashed` flag should be limited.
